import { Injectable } from '@angular/core';
import { BehaviorSubject, Subject } from 'rxjs';
import { PRODUCT_MODEL } from 'src/abstract_classes/product.model';

@Injectable({
  providedIn: 'root'
})
export class ProductFilterService {
  // THE @INJECTABLE DECORATOR INDICATES THAT THIS CLASS IS INJECTABLE AS A SERVICE

  // THE BEHAVIORSUBJECT AND SUBJECT ARE IMPORTED FROM THE RXJS LIBRARY. THESE ARE USED FOR CREATING OBSERVABLE STREAMS THAT CAN EMIT VALUES TO SUBSCRIBERS

  // PRODUCT_MODEL IS IMPORTED FROM THE 'SRC/ABSTRACT_CLASSES/PRODUCT.MODEL' FILE. IT REPRESENTS THE TYPE OR INTERFACE USED FOR THE PRODUCTS IN THE APPLICATION

  // THE FILTEREDPRODUCTSSUBJECT IS A PRIVATE INSTANCE VARIABLE OF TYPE BEHAVIORSUBJECT THAT HOLDS THE CURRENT FILTERED PRODUCTS. IT IS INITIALIZED WITH AN EMPTY ARRAY []

  // FILTEREDPRODUCTS$ IS A PUBLIC OBSERVABLE PROPERTY THAT EXPOSES THE FILTEREDPRODUCTSSUBJECT AS AN OBSERVABLE STREAM. OTHER COMPONENTS OR SERVICES CAN SUBSCRIBE TO THIS PROPERTY TO RECEIVE UPDATES WHEN THE FILTERED PRODUCTS CHANGE.

  // THE UPDATEFILTEREDPRODUCTS METHOD TAKES AN ARRAY OF PRODUCT_MODEL AS AN ARGUMENT AND UPDATES THE FILTEREDPRODUCTSSUBJECT BY CALLING NEXT() ON IT WITH THE NEW ARRAY. THIS METHOD IS USED TO UPDATE THE FILTERED PRODUCTS AND EMIT THE UPDATED VALUES TO SUBSCRIBERS OF FILTEREDPRODUCTS$
  private filteredProductsSubject = new BehaviorSubject<PRODUCT_MODEL[]>([]);
  filteredProducts$ = this.filteredProductsSubject.asObservable();

  updateFilteredProducts(filteredProducts: PRODUCT_MODEL[]) {
    this.filteredProductsSubject.next(filteredProducts);
  }
}
